version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      resource_class: large

    steps:
      - run:
          name: Install the AOSP build dependencies
          command: sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo -y

      - run:
          name: Download Pixel Experience manifest
          no_output_timeout: 2h
          command: repo init -u https://github.com/PixelExperience/manifest -b thirteen

      - run:
          name: Sync it
          no_output_timeout: 24h
          command: repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --depth=1 -c

      - run:
          name: Optimize Disk
          command: rm -rfv .repo

      - run:
          name: Pull Samsung A03s Device Tree
          command: git clone https://github.com/ArcticAquila/android_device_samsung_a03s device/samsung/a03s --depth=1

      - run:
          name: Set up the AOSP build environment
          command: source build/envsetup.sh

      # PLEASE THIS IS ONLY FOR TEMPORARY
      # Remove recovery.fstab
      - run:
          name: Remove Conflict Files (TEMPORARY)
          command: echo "" > device/samsung/a03s/recovery/system/etc/recovery.fstab

      - run:
          name: Lunch target device
          no_output_timeout: 2h
          command: lunch aosp_a03s-userdebug

      - run:
          name: Build PixelExperience
          no_output_timeout: 7h
          command: mka bacon -j$(nproc --all)

      - store_artifacts:
          path: out/target/product/a03s/PixelExperience_a03s-13.0-20231129-1907-UNOFFICIAL.zip

      - store_artifacts:
          path: out/target/product/a03s/PixelExperience_a03s-13.0-20231129-1907-UNOFFICIAL.zip.sha256sum

workflows:
  build_and_test:
    jobs:
      - build
